# -*- coding: utf-8 -*-
"""EvidenciaFinalUF6_A01707744.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kCYB27VYFx4vGCCA_chLSaZilJQfDX49
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#ssl.OPENSSL_VERSION = ssl.OPENSSL_VERSION.replace("LibreSSL", "OpenSSL")

#st.title('The Police Incident Reports from 2018 to 2020 in San Francisco')
st.markdown("<h1 style='color: red;'>The Police Incident Reports from 2018 to 2020 in San Francisco</h1>", unsafe_allow_html=True)

df = pd.read_csv("Police_Department_Incident_Reports__2018_to_Present.csv")
#st.dataframe(df)

#st.markdown('The data shown below belongs to incident reports in the city of San Francisco, from the year 2018 to 2020, with details from each case such as date, day of the week, police district, neighborhood in which it happened, type of incident in category and subcategory, exact location and resolution.')
st.markdown("<p style='color: blue; font-size: 16px;'>The data shown below belongs to incident reports in the city of San Francisco, from the year 2018 to 2020, with details from each case such as date, day of the week, police district, neighborhood in which it happened, type of incident in category and subcategory, exact location and resolution.</p>", unsafe_allow_html=True)

mapa = pd.DataFrame()
mapa['Date'] = df['Incident Date']
mapa['Day'] = df['Incident Day of Week']
mapa['Police District'] = df['Police District']
mapa['Neighborhood'] = df['Analysis Neighborhood']
mapa['Incident Category'] = df['Incident Category']
mapa['Incident Subcategory'] = df['Incident Subcategory']
mapa['Resolution'] = df['Resolution']
mapa['lat'] = df['Latitude']
mapa['lon'] = df['Longitude']
mapa = mapa.dropna()

subset_data2 = mapa
police_district_input = st.sidebar.multiselect(
'Police District',
mapa.groupby('Police District').count().reset_index()['Police District'].tolist())
if len(police_district_input) > 0:
    subset_data2 = mapa[mapa['Police District'].isin(police_district_input)]

subset_data1 = subset_data2
neighborhood_input = st.sidebar.multiselect(
'Neighborhood',
subset_data2.groupby('Neighborhood').count().reset_index()['Neighborhood'].tolist())
if len(neighborhood_input) > 0:
    subset_data1 = subset_data2[subset_data2['Neighborhood'].isin(neighborhood_input)]

subset_data = subset_data1
incident_input = st.sidebar.multiselect(
'Incident Category',
subset_data1.groupby('Incident Category').count().reset_index()['Incident Category'].tolist())
if len(incident_input) > 0:
    subset_data = subset_data1[subset_data1['Incident Category'].isin(incident_input)]
            
subset_data

# Tamaño y tipo de letra 
st.markdown("<style>body {font-size: 18px !important; font-family: Arial, sans-serif !important;}</style>", unsafe_allow_html=True)

# color y tamaño del título y graficas 

st.markdown('It is important to mention that any police district can answer to any incident, the neighborhood in which it happened is not related to the police district.')    
st.markdown("<h3 style='color: green;'>Crime locations in San Francisco</h3>", unsafe_allow_html=True)
st.map(subset_data)

st.bar_chart(subset_data['Day'].value_counts())
st.markdown("<h3 style='color: purple;'>Crimes ocurred per day of the week</h3>", unsafe_allow_html=True)

st.line_chart(subset_data['Date'].value_counts())
st.markdown("<h3 style='color: orange;'>Crimes ocurred per date</h3>", unsafe_allow_html=True)

st.bar_chart(subset_data['Incident Category'].value_counts())
st.markdown("<h3 style='color: brown;'>Type of crimes committed</h3>", unsafe_allow_html=True)


agree = st.button('Click to see Incident Subcategories')
if agree:
    st.markdown('Subtype of crimes committed')
    st.bar_chart(subset_data['Incident Subcategory'].value_counts())

agree2 = st.button('Click to see Incident Day of the week')
if agree2:
    st.markdown('Crimes ocurred per day of the week')
    st.line_chart(subset_data['Day'].value_counts())

agree3 = st.button('Click to see Incident ocurred per Date')
if agree3:
    st.markdown('Crimes committed Date')
    st.line_chart(subset_data['Date'].value_counts())

st.markdown('Resolution status')
fig1, ax1 = plt.subplots()
labels = subset_data['Resolution'].unique()
ax1.pie(subset_data['Resolution'].value_counts(), labels=labels, autopct='%1.1f%%', startangle=20)
ax1.axis('equal')

# Modificar el color de las porciones del gráfico de pastel
colors = ['#FFB3BA', '#FFDFBA', '#FFFFBA', '#BAFFC9', '#BAE1FF']
ax1.pie(subset_data['Resolution'].value_counts(), labels=labels, autopct='%1.1f%%', startangle=20, colors=colors)

st.pyplot(fig1)